gerador_clipping/gerador/urls.py
"""" Para onde cada URL deve direcionar o usuário. """
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'gerador'
urlpatterns = [
    path('', views.ExplorerView.as_view(), name='explorer'),
    path('<int:project_id>/show_rename/',
         views.show_rename_project, name='show_rename_project'),
    path('<int:project_id>/rename/',
         views.rename_project, name='rename_project'),
    path('new_project/', views.new_project, name='new_project'),
    path('<int:project_id>/archive/',
         views.archive_project, name='archive_project'),
    path('<int:project_id>/show_archive/',
         views.show_archive_project, name='show_archive_project'),
    path('<int:project_id>/duplicate/',
         views.duplicate_project, name='duplicate_project'),
    path('<int:project_id>/insert_news/',
         views.insert_news, name='insert_news'),
    path('<int:project_id>/clipping_organizer/',
         views.clipping_organizer, name='clipping_organizer'),
    path('<int:project_id>/remove_news/',
         views.remove_news, name='remove_news'),
    path('<int:project_id>/update_image_news/',
         views.update_image_news, name='update_image_news'),
    path('<int:project_id>/news_order_up/',
         views.news_order_up, name='news_order_up'),
    path('<int:project_id>/update_header/',
         views.update_header, name='update_header'),
    path('<int:project_id>/download_pdf/',
         views.download_pdf, name='download_pdf'),
    path('<int:project_id>/download_jpeg/',
         views.download_jpeg, name='download_jpeg'),

    path('<int:project_id>/show_organization_identity/',
         views.show_organization_identity, name='show_organization_identity'),

    path('<int:project_id>/update_organization_identity/',
         views.update_organization_identity, name='update_organization_identity'),
    path('<int:project_id>/recovery/', views.news_recovery, name='news_recovery'),
    path('<int:project_id>/organizer/',
         views.clipping_organizer, name='organizer'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gerador_clipping/gerador_clipping/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('gerador.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gerador_clipping/gerador/models.py
#!-*- conding: utf8 -*-
"""" Os modelos dos dados do aplicativo. """

from io import BytesIO

from django.db import models
from django.core.files.base import ContentFile
from django.core.files.uploadedfile import InMemoryUploadedFile

from PIL import Image


class ClippingProject(models.Model):
    """" O projeto do clipping em produção. Possui nome, data e conteúdo. """
    name = models.CharField(max_length=100)

    created_date = models.DateTimeField('date created')
    is_archived = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class News(models.Model):
    """" News é uma notícia do clipping. É serializada como XML para o Jaspersoft Studio"""
    project = models.ForeignKey(ClippingProject, on_delete=models.CASCADE)
    order = models.PositiveSmallIntegerField(default=0)
    title = models.CharField(max_length=500)
    content = models.CharField(max_length=500)
    url = models.CharField(max_length=500)
    pub_date = models.DateTimeField('published date')
    human_pub_date = models.CharField(max_length=500, default='0')
    author = models.CharField(max_length=500, default='0')
    url_to_image = models.CharField(max_length=500, default='0')
    image = models.ImageField(
        upload_to='gerador/jasper/images', blank=True, max_length=1000)
    source_db_id = models.CharField(max_length=500, default='0')
    header = models.CharField(max_length=500, default="")
    clipping_creator = models.CharField(
        max_length=2000, default="Elaborado por <br> Sala de Situação da FS/UnB")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["order"]

    def crop_image(self):
        """ Recorta imagem para 16:9"""
        img = Image.open(self.image)
        img = img.convert('RGB')
        # Size of the image in pixels (size of orginal image)
        # (This is not mandatory)
        width, height = img.size
        left = 0
        top = 0
        right = width
        bottom = height
        if width >= height * 16/9:
            # imagem muito horizontal, recorta esquerda e direita
            new_width = int(height*(16/9))
            left = int((width-new_width)/2)
            right = width-left

        else:
            # imagem muito vertical, recorta cima e baixo
            new_height = int(width/(16/9))
            top = int((height-new_height)/2)
            bottom = height-top

        cropped_image = img.crop(
            (left, top, right, bottom))

        buffer = BytesIO()
        cropped_image.save(fp=buffer, format='JPEG')

        pillow_image = ContentFile(buffer.getvalue())

        self.image.save(self.image.name, InMemoryUploadedFile(
            pillow_image,
            None,
            self.image.name,
            'image/jpeg',
            pillow_image.tell,
            None
        ))
        self.url_to_image = self.image.url
        self.save()


class OrganizationIdentity(models.Model):
    """ Representa a identidade da organização criadora dos clippings. """
    clipping_creator = models.CharField(
        max_length=2000, default='Sala de Situação da FS/UnB')

gerador_clipping/gerador/views.py
"""" As views gerenciam o que ocorre quando o usuário entra em uma URL do app"""
import datetime
import os
import tempfile
import zipfile
import socket
import requests


from pdf2image import convert_from_path

from pyreportjasper import JasperPy

from django.http import HttpResponseRedirect, HttpResponse, FileResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.core import serializers, files


from django.utils import timezone
from django.urls import reverse
from django.views import generic

from .models import ClippingProject, News, OrganizationIdentity


class ExplorerView(generic.ListView):
    """" Permite gerenciar projetos de clipping. """

    template_name = 'gerador/explorer.html'
    context_object_name = 'project_list'

    def get_queryset(self):
        """ Retornar os 1000 projetos mais recentes. """
        return ClippingProject.objects.order_by('-created_date')[0:1000]


def new_project(request):
    """ Cria novo projeto e redireciona para tela de edição. """
    if OrganizationIdentity.objects.count() == 0:
        new_organization_identity = OrganizationIdentity()
        new_organization_identity.save()

    name = request.POST.get('clipping_name', str(
        ClippingProject.objects.count()+1))
    created_date = timezone.now()
    project = ClippingProject(name=name, created_date=created_date)
    project.save()

    # Por enquanto redireciona para o explorador, mas deve já abrir o clipping para edição
    return HttpResponseRedirect(reverse('gerador:explorer'))


def show_rename_project(request, project_id):
    """ Exibe tela de renomear projeto """
    project = ClippingProject.objects.get(id=project_id)

    return render(request, 'gerador/rename_project.html',
                  {'project': project})


def duplicate_project(request, project_id):
    """" Duplica projeto. """
    project = ClippingProject.objects.get(id=project_id)
    project.pk = None

    project.name = 'Cópia de ' + project.name
    project.created_date = timezone.now()
    project.save()
    return HttpResponseRedirect(reverse('gerador:explorer'))


def rename_project(request, project_id):
    """" Renomeia projeto. """
    project = ClippingProject.objects.get(id=project_id)
    project.name = request.POST.get('new_name')
    project.save()
    return HttpResponseRedirect(reverse('gerador:explorer'))


def show_archive_project(request, project_id):
    """" Tela para confirmar arquivamento do projeto. """
    project = ClippingProject.objects.get(id=project_id)

    return render(request, 'gerador/delete_confirmation.html',
                  {'project': project, })


def archive_project(request, project_id):
    """" Arquiva projeto. """
    project = ClippingProject.objects.get(id=project_id)
    project.is_archived = True
    project.save()
    return HttpResponseRedirect(reverse('gerador:explorer'))


def news_recovery(request, project_id):
    """" Permite recuperar as notícias do banco de dados com parâmetros. """
    project = get_object_or_404(ClippingProject, pk=project_id)
    hostname = socket.gethostname()
    ip_addr = socket.gethostbyname(hostname)
    ip_split = ip_addr.split('.')
    try:
        params = {'page': request.GET.get('page', 1), 'items': 5000}
        is_connected = False

        address_to_try = request.session.get('bd_address', 0)
        while not is_connected:
            url = 'http://'+ip_split[0] + '.' + ip_split[1] + \
                '.' + ip_split[2] + '.' + \
                str(address_to_try) + ":8080/noticias"
            try:
                api_request = requests.get(url=url, params=params)
            except requests.exceptions.RequestException:
                request.session['bd_address'] = 1

                address_to_try += 1
                if address_to_try == 7:  # Excedeu o limite de tentativas
                    raise requests.exceptions.RequestException

            else:
                request.session['bd_address'] = address_to_try
                is_connected = True

        raw_data = api_request.json()

        news_list = raw_data['data']

        search_age = int(request.GET.get('age', request.session.get('age', 7)))
        request.session['age'] = search_age

        # Filtro por Idade
        for i in range(len(news_list) - 1, -1, -1):
            found_term = False
            # formatar tempo para humanos e para django
            date_time_str = news_list[i]['publishedAt']

            date_time_obj = datetime.datetime.strptime(
                date_time_str, '%Y-%m-%dT%H:%M:%SZ')

            date_difference = datetime.datetime.now(
                date_time_obj.tzinfo) - date_time_obj

            if date_difference.days > search_age:
                del news_list[i]
                continue

            news_list[i]['publishedAt_human'] = date_time_obj
            news_list[i]['age_minutes'] = date_difference.days * \
                60*24 + date_difference.seconds/60

        search_term_packed = request.GET.get(
            'search_term', request.session.get('search_term', ''))
        request.session['search_term'] = search_term_packed
        search_terms = search_term_packed.split()

        # Filtro por search_term
        if len(search_terms) > 0:
            for i in range(len(news_list) - 1, -1, -1):
                found_term = False
                for search_term in search_terms:
                    if search_term in news_list[i]['title'] or \
                            search_term in news_list[i]['content']:
                        found_term = True
                        break

                if found_term:
                    continue

                del news_list[i]

        # Ordena por score ou published_at
        sort = request.GET.get('sort', request.session.get('sort', 'score'))
        request.session['sort'] = sort

        if sort == 'score':
            news_list = sorted(news_list, key=lambda k: k['score'])
        else:
            news_list = sorted(news_list, key=lambda k: k['age_minutes'])

        # configura detalhes nas notícias filtradas
        for news in news_list:

            # Marca notícias que já foram inclusas
            news['is_included'] = project.news_set.filter(
                source_db_id=news['id']).count() > 0

            # remover [+N chars]
            content = news['content']
            if content.find('[+'):
                content = content.split('[+')[0]
                news['content'] = content

            # Curar tamanho da string
            paragraphs = content.split('\n')
            curated_content = ''
            while len(curated_content) < len(content)/2:
                curated_content = paragraphs.pop(0)

            curated_content = curated_content.rstrip() + ' '

            news['content'] = curated_content

        return render(request, 'gerador/news_recovery.html',
                      {'project': project, 'news_result': news_list,
                       'search_terms': search_term_packed,
                       'age': search_age,
                       'sort': sort})

    except requests.exceptions.RequestException:

        return HttpResponse("Erro ao conectar ao Banco de Dados HealthNewsAPI."
                            " Verifique se o serviço está executando e se há internet.")


def insert_news(request, project_id):
    """" Insere notícia no projeto. """

    project = ClippingProject.objects.get(id=project_id)
    current_identity = OrganizationIdentity.objects.all()[0]
    title = request.POST.get('title')
    content = request.POST.get('content')

    author = request.POST.get('author')
    url = request.POST.get('url')
    pub_date = request.POST.get('publishedAt')
    url_to_image = request.POST.get('urlToImage')
    source_db_id = request.POST.get('source_db_id')
    human_pub_date = request.POST.get('human_pub_date')
    order = project.news_set.all().count()

    created_news = News(project=project,
                        title=title,
                        content=content,
                        url=url,
                        pub_date=pub_date,
                        author=author,
                        url_to_image=url_to_image,
                        source_db_id=source_db_id,
                        order=order,
                        human_pub_date=human_pub_date,
                        clipping_creator=current_identity.clipping_creator)

    # Primeiro verifica se já temos uma imagem similar salva
    file_name = url_to_image[8:]

    try:
        request = requests.get(url_to_image, stream=True)
    except requests.exceptions.RequestException:
        return HttpResponse("Erro ao baixar imagem da notícia."
                            " Verifique se há internet.")

    if request.status_code != 200:
        raise BaseException("Erro ao carregar imagem: " +
                            request.status_code + url_to_image)

    temporary_file = tempfile.NamedTemporaryFile()
    for block in request.iter_content(1024 * 8):
        if not block:
            break

        temporary_file.write(block)

    created_news.image.save(file_name, files.File(temporary_file))
    created_news.save()
    created_news.crop_image()
    return HttpResponseRedirect(reverse('gerador:news_recovery', args=[project_id]))


def remove_news(request, project_id):
    """" Insere notícia no projeto. """

    project = get_object_or_404(ClippingProject, pk=project_id)

    source_db_id = request.POST.get('source_db_id')

    news_to_remove = project.news_set.filter(
        source_db_id=source_db_id)

    for news in news_to_remove:
        order_of_deleted_news = news.order
        news.image.delete()
        news.delete()
        news_to_reorder = project.news_set.filter(
            order__gt=order_of_deleted_news)
        for other_news in news_to_reorder:
            other_news.order -= 1
            other_news.save()

    return redirect(request.META.get('HTTP_REFERER'))

gerador_clipping/gerador/templates/gerador/clipping_organizer.html
{% load humanize %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" href="images/favicon.ico" type="image/ico" />

    <title>Ordenador de Notícias</title>

    <!-- Bootstrap -->
    <link href="{% static 'gerador/Assets/gentelella/vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'gerador/Assets/gentelella/vendors/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'gerador/Assets/gentelella/vendors/nprogress/nprogress.css'%}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'gerador/Assets/gentelella/vendors/iCheck/skins/flat/green.css'%}" rel="stylesheet">
  
    <!-- bootstrap-progressbar -->
    <link href="{% static 'gerador/Assets/gentelella/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css'%}" rel="stylesheet">
    <!-- JQVMap -->
    <link href="{% static 'gerador/Assets/gentelella/vendors/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="{% static 'gerador/Assets/gentelella/vendors/bootstrap-daterangepicker/daterangepicker.css'%}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'gerador/Assets/gentelella/build/css/custom.min.css'%}" rel="stylesheet">
  </head>

  <body class="nav-md" style="background-color: white;">

<!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3 style="text-align: center;">Ordene as notícias e insira cabeçalhos</h3>
              </div>

              <div class="title_right">
              </div>
            </div>
            <a href="{% url 'gerador:explorer' %}"><input type="button" class="btn btn-default" value="Voltar ao explorador de projetos"></a>
            
            <a href="{% url 'gerador:news_recovery' project.id %}"><input type="button" class="btn btn-default" value="Recuperar mais notícias"></a>
            <a href="{% url 'gerador:show_organization_identity' project.id %}"><input type="button" class="btn btn-default" value="Atualizar Créditos"></a>
            <a href="{% url 'gerador:download_pdf' project.id %}"><input type="button" class="btn btn-primary" value="Gerar Clipping PDF"></a>
            <br>

            {% for news in news_set  %}
            <div class="clearfix"></div>
            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>{{news.title}}</h2>
                    <ul class="nav navbar-right panel_toolbox">
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <table width="100%">
                      <tr>
                      <td style="width:20%;"><img src="{{ news.url_to_image }}" height="140"></td>
                      <td style="width:67%">
                      <form action="{% url 'gerador:update_header' project.id%}" method="post">
                          {% csrf_token %}
                          <label for="header">Tópico:</label>
                          <input type="text" name="header" id="header" value="{{ news.header }}" required minlength="1"/>
                          <input type="hidden" name="order" value="{{ news.order }}" />
                          <input type="submit" class="btn btn-primary" onclick="this.disabled=true,this.form.submit();" value="Atualizar"/>
                      </form>
                      <form action="{% url 'gerador:update_image_news' project.id%}" method="post" enctype="multipart/form-data">
                          {% csrf_token %}
                          <label for="new_image">Nova Imagem:</label>
                          <input type="hidden" name="order" value="{{ news.order }}" />
                          <input type="file" name="new_image" id="new_image" accept="image/*" required minlength="1">
                          <input type="submit" class="btn btn-primary" onclick="this.disabled=true,this.form.submit();" value="Atualizar Imagem"/>
                      </form>
                      </td>
                      <td style="width:23%;text-align:center">
                        <form action="{% url 'gerador:remove_news' project.id%}" method="post">
                             {% csrf_token %}
                             
                              <input type="hidden" name="source_db_id" value="{{ news.source_db_id }}" />
                              <input type="submit" class="btn btn-danger" onclick="this.disabled=true,this.form.submit();" value="Remover"/>
                        </form>
            
                        {% if news.order > 0%}
                        <form action="{% url 'gerador:news_order_up' project.id%}" method="post">
                             {% csrf_token %}
                             
                              <input type="hidden" name="order" value="{{ news.order }}" />
                              <input type="submit" class="btn btn-success" onclick="this.disabled=true,this.form.submit();" value="Subir"/>
                        </form>
                        {% endif %}
                        {% if not forloop.last %}
                        <form action="{% url 'gerador:news_order_up' project.id%}" method="post">
                             {% csrf_token %}
                             
                              <input type="hidden" name="order" value="{{ news.order|add:"1" }}" />
                              <input type="submit" class="btn btn-warning" onclick="this.disabled=true,this.form.submit();" value="Descer"/>
                        </form>
                        {% endif %}
                      </td>
                      </tr>
                    </table>
                  </div>

                </div>
              </div>
            </div>
            {% endfor%}

            </div>

        <!-- /page content -->

        <!-- Linha para fazer o javascript funcionar -->
        <a id="download" href="javascript:void(0);" download="cropped.png"></a>

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            CENTEIAS 2019
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>
    <!-- jQuery -->
    <script src="{% static '/gerador/Assets/gentelella/vendors/jquery/dist/jquery.min.js'%}"></script>
    <!-- Bootstrap -->
    <script src="{% static '/gerador/Assets/gentelella/vendors/bootstrap/dist/js/bootstrap.min.js'%}"></script>
    <!-- FastClick -->
    <script src="{% static '/gerador/Assets/gentelella/vendors/fastclick/lib/fastclick.js'%}"></script>
    <!-- NProgress -->
    <script src="{% static '/gerador/Assets/gentelella/vendors/nprogress/nprogress.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static '/gerador/Assets/gentelella/vendors/iCheck/icheck.min.js'%}"></script>
    <!-- Datatables -->
    <script src="{% static '/gerador/Assets/gentelella/vendors/datatables.net/js/jquery.dataTables.min.js'%}"></script>
    <script src="{% static '/gerador/Assets/gentelella/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js'%}"></script>
    <script src="{% static '/gerador/Assets/gentelella/vendors/datatables.net-buttons/js/dataTables.buttons.min.js'%}"></script>
    <script src="{% static '/gerador/Assets/gentelella/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js'%}"></script>
    <script src="{% static '/gerador/Assets/gentelella/vendors/datatables.net-buttons/js/buttons.flash.min.js'%}"></script>
    <script src="{% static '/gerador/Assets/gentelella/vendors/datatables.net-buttons/js/buttons.html5.min.js'%}"></script>
    <script src="{% static '/gerador/Assets/gentelella/vendors/datatables.net-buttons/js/buttons.print.min.js'%}"></script>
    <script src="{% static '/gerador/Assets/gentelella/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js'%}"></script>
    <script src="{% static '/gerador/Assets/gentelella/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js'%}"></script>
    <script src="{% static '/gerador/Assets/gentelella/vendors/datatables.net-responsive/js/dataTables.responsive.min.js'%}"></script>
    <script src="{% static '/gerador/Assets/gentelella/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
    <script src="{% static '/gerador/Assets/gentelella/vendors/datatables.net-scroller/js/dataTables.scroller.min.js'%}"></script>
    <script src="{% static '/gerador/Assets/gentelella/vendors/jszip/dist/jszip.min.js'%}"></script>
    <script src="{% static '/gerador/Assets/gentelella/vendors/pdfmake/build/pdfmake.min.js'%}"></script>
    <script src="{% static '/gerador/Assets/gentelella/vendors/pdfmake/build/vfs_fonts.js'%}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{% static '/gerador/Assets/gentelella/build/js/custom.min.js' %}"></script>
	
  </body>
</html>

gerador_clipping/gerador/templates/gerador/delete_confirmation.html
<h3>Tem certeza?</h3>
<p>Você não poderá recuperar este projeto!</p>

<form action="{% url 'gerador:explorer'  %}" method="get">
    <input type="submit" value="Cancelar">
</form>

<form action="{% url 'gerador:archive_project' project.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Sim, delete!">
</form>

gerador_clipping/gerador/templates/gerador/organization_identity.html
<h1> Créditos dos criadores do clipping</h1>

<form action="{% url 'gerador:update_organization_identity' project.id %}" method="post">

    {% csrf_token %}
    <label for="clipping_creator">Créditos do final do clipping:</label>
    <br>
    <textarea name="clipping_creator" id="clipping_creator" rows="10" cols="50" required>{{identity.clipping_creator}}
    </textarea>
    <br>
    <p>Este campo permite tags de HTML:</p>
    <ul>
        <li>&lt;b&gt; <b> Negrito </b>&lt;/b&gt;
        <li>&lt;u&gt; <u> Underline </u>&lt;/u&gt;
        <li>&lt;i&gt; <i> Itálico </i>&lt;/i&gt;
        <li>Quebra de &lt;br&gt; <br>linha
        
    </ul>
    <input type="submit" value="Salvar">


</form>

gerador_clipping/gerador/templates/gerador/rename_project.html
<h1> Renomear projeto de clipping</h1>

<form action="{% url 'gerador:rename_project' project.id %}" method="post">

    {% csrf_token %}
    <label for="old_name">Nome Atual:</labe>
    <input type="text" name="old_name" id="old_name" value ="{{ project.name }}" readonly disabled>

    <br>
    <label for="new_name">Nome Novo:</labe>
    <input type="text" name="new_name" id="new_name" value ="" required>
                                    
    <input type="submit" value="Salvar">


</form>